export const CREATE_COURSE = 'CREATE_COURSE';
export const GET_COURSES_LIST = 'GET_COURSES_LIST';
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
